In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [3]:
block_size = 8
batch_size = 4

In [4]:
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(set(text))
print(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [5]:
s2i = {ch:i for i, ch in enumerate(chars)}
i2s = {i:ch for ch, i in enumerate(chars)}
encode = lambda x: [s2i[c] for c in x]
decode = lambda x: [i2s[i] for i in x]

encode('hello')

[61, 58, 65, 65, 68]

In [6]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,  1, 47, 33,
        50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26, 49,  0,  0,
         1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,  0,  0,  1,
         1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1, 47, 33, 50,
        25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1, 36, 25, 38,
        28,  1, 39, 30,  1, 39, 50,  9,  1, 39])


In [15]:
n = int(0.8*len(data))
train_data = data[:n]
test_data = data[n:]

In [22]:

x = train_data[:block_size]
y = train_data[1:block_size+1]

def get_batch(split):
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x,y = get_batch('train')
x, y

tensor([119528,  23102, 152870, 128856])


(tensor([[ 1, 69, 74, 65, 65,  1, 73, 61],
         [ 1, 55, 71, 62, 65, 65, 62, 54],
         [66, 58,  1, 73, 68,  1, 58, 77],
         [ 1, 54, 59, 73, 58, 71,  1, 73]], device='cuda:0'),
 tensor([[69, 74, 65, 65,  1, 73, 61, 58],
         [55, 71, 62, 65, 65, 62, 54, 67],
         [58,  1, 73, 68,  1, 58, 77, 54],
         [54, 59, 73, 58, 71,  1, 73, 62]], device='cuda:0'))

In [9]:
tensor = torch.Tensor([1, 2, 3])
F.softmax(tensor, dim=0)

tensor([0.0900, 0.2447, 0.6652])

In [12]:
a = torch.Tensor([[1, 2], [3, 4], [5, 6]])
b = torch.Tensor([[7, 8, 9], [10, 11, 12]])

a@b, torch.matmul(a, b)

(tensor([[ 27.,  30.,  33.],
         [ 61.,  68.,  75.],
         [ 95., 106., 117.]]),
 tensor([[ 27.,  30.,  33.],
         [ 61.,  68.,  75.],
         [ 95., 106., 117.]]))